server:
  port: 0

spring:
  application:
    name: eureka-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/, http://eureka1.example.com:9001/eureka/, http://eureka2.example.com:9002/eureka/
